name: .NET Release Creation

on:
  workflow_call:
    inputs:
      solutionPath:
        required: true
        type: string
      nugetPackageName:
        required: true
        type: string
      projectToPackagePath:
        required: true
        type: string

jobs:
  release:
    name: Create and Publish Packages
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
      checks: write
      packages: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.13
    - name: Adjust NuGet Config Credentials
      run: |
        rm -f ./nuget.config
        mv nuget.ci.config nuget.config
        echo $(sed -e "s/\${USER}/${{ secrets.TC_NUGET_USER }}/" -e "s@\${PAT}@${{ secrets.TC_NUGET_PASSWORD }}@" -e "s@\${GH_PAT}@${{ secrets.GHACTION_REPO }}@" nuget.config) >nuget.config
    
    - name: Restore dependencies
      run: dotnet restore ${{ inputs.solutionPath }}
    - name: Build
      run: dotnet build --no-restore --configuration Release ${{ inputs.solutionPath }}

    - name: Package API
      run:  dotnet pack --no-build --configuration Release -o ./ -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg /p:VersionPrefix="${{ steps.gitversion.outputs.nuGetVersionV2 }}" ${{ inputs.projectToPackagePath }}
    - name: Publish Nuget Package
      run: dotnet nuget push "${{ inputs.nugetPackageName }}.${{ steps.gitversion.outputs.nuGetVersionV2 }}.nupkg" --api-key "${{ secrets.GITHUB_TOKEN }}" --source "Kno2-GitHub"
    - name: Publish Symbol Package
      run: dotnet nuget push "${{ inputs.nugetPackageName }}.${{ steps.gitversion.outputs.nuGetVersionV2 }}.snupkg" --api-key "${{ secrets.GITHUB_TOKEN }}" --source "Kno2-GitHub"
