
name: Pull Request Build

on:
  workflow_call:
    inputs:
      solutionPath:
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Adjust NuGet Config Credentials
      run: |
        rm -f ./nuget.config
        mv nuget.ci.config nuget.config
        echo $(sed -e "s/\${USER}/${{ secrets.TC_NUGET_USER }}/" -e "s@\${PAT}@${{ secrets.TC_NUGET_PASSWORD }}@" -e "s@\${GH_PAT}@${{ secrets.GHACTION_REPO }}@" nuget.config) >nuget.config
    
    - name: Restore dependencies
      run: dotnet restore ${{ inputs.solutionPath }}
    - name: Build
      run: dotnet build --no-restore ${{ inputs.solutionPath }}
    
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger:"trx;LogFileName=TestResults.trx" ${{ inputs.solutionPath }}
    
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        trx_files: "src/**/TestResults/*.trx"