name: .NET Release Creation

on:
  workflow_call:
    inputs:
      solutionPath:
        required: true
        type: string
      nugetPackageName:
        required: true
        type: string
      projectToPackagePath:
        required: true
        type: string
      buildWhenPacking:
        description: Whether to build the release again when packing
        type: boolean
        required: false
        default: false

jobs:
  release:
    name: Create and Publish Packages
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
      checks: write
      packages: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          3.1.x
          6.0.x

    - uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.13
    
    - name: Adjust NuGet Config Credentials
      run: |
        mv nuget.ci.config nuget.config
        (Get-Content nuget.config) -replace '\${USER}', "${{ secrets.TC_NUGET_USER }}" -replace '\${PAT}', "${{ secrets.TC_NUGET_PASSWORD }}" -replace '\${GH_PAT}', "${{ secrets.GHACTION_REPO }}" | Out-File nuget.config
    
    - name: Restore dependencies
      run: dotnet restore ${{ inputs.solutionPath }}
    - name: Build
      run: dotnet build --no-restore --configuration Release ${{ inputs.solutionPath }}

    - name: Package API
      if: ${{ ! inputs.buildWhenPacking }}
      run:  dotnet pack --no-build --configuration Release -o ./ -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg /p:VersionPrefix="${{ steps.gitversion.outputs.nuGetVersionV2 }}" ${{ inputs.projectToPackagePath }}
    
    - name: Package with Build
      if: ${{ inputs.buildWhenPacking }}
      run:  dotnet pack --configuration Release -o ./ -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg /p:VersionPrefix="${{ steps.gitversion.outputs.nuGetVersionV2 }}" ${{ inputs.projectToPackagePath }}

    - name: Publish Nuget Package
      run: dotnet nuget push "${{ inputs.nugetPackageName }}.${{ steps.gitversion.outputs.nuGetVersionV2 }}.nupkg" --api-key "${{ secrets.GITHUB_TOKEN }}" --source "Kno2-GitHub"
    
    - name: Publish Symbol Package
      run: dotnet nuget push "${{ inputs.nugetPackageName }}.${{ steps.gitversion.outputs.nuGetVersionV2 }}.snupkg" --api-key "${{ secrets.GITHUB_TOKEN }}" --source "Kno2-GitHub"

    - name: Upload NugetPackage to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "${{ inputs.nugetPackageName }}.${{ steps.gitversion.outputs.nuGetVersionV2 }}"
        path: "${{ inputs.nugetPackageName }}.${{ steps.gitversion.outputs.nuGetVersionV2 }}.nupkg"
        retention-days: 1